config/routes.rb
Rails.application.routes.draw do

  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#new'

  get 'repositories/index'
  get 'repositories/show'

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    @repositories = []
    if current_user.present?
      auth_result = JSON.parse(RestClient.get('https://api.github.com/user/repos', {:params => {:access_token => current_user.oauth_token } }))
      auth_result.each do |x|
        @repositories << {name: x['name'], full_name: x['full_name']}
      end
    else
      redirect_to root_path, :notice => "Unauthorized."
    end
  end

  def show
    @repository = nil
    @repository_commits = []
    if current_user.present?
      url = "https://api.github.com/repos/#{params[:format]}"
      auth_result = JSON.parse(RestClient.get(url, {:params => {:access_token => current_user.oauth_token } }))

      @repository = {name: auth_result['name'], description: auth_result['description']}

      commits_url = "https://api.github.com/repos/#{params[:format]}/commits"
      repo_commits = JSON.parse(RestClient.get(commits_url , {:params => {:access_token => current_user.oauth_token } }))
      repo_commits.each do |x|
        @repository_commits << {commit_msg: x['commit']['message'], commit_date: x['commit']['author']['date']}
      end
    else
      redirect_to root_path, :notice => "Unauthorized."
    end

  end

  # "commits_url": "https://api.github.com/repos/benlcollins/github_api_viz/commits{/sha}",
  # "git_commits_url": "https://api.github.com/repos/benlcollins/github_api_viz/git/commits{/sha}",
  # GET /repos/:owner/:repo/commits
  # https://api.github.com/repos/kaushalkishorersmt/github_api_viz
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      # redirect_to request.env['omniauth.origin']
      redirect_to repositories_index_path
    end
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserRepository</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repositories/index.html.erb
<h1>Repositories List ( <%= current_user.username %> )</h1>
  <%= button_to "Sign Out", signout_path, method: :delete %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <p>Name</p>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td>
          <%= link_to repository[:name], repositories_show_path(repository[:full_name]) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/repositories/show.html.erb
<h1>Repository Details ( <%= current_user.username %> )</h1>
  <%= button_to "Sign Out", signout_path, method: :delete %>

<table class="table table-striped">
  <thead border="1">
    <tr>
      <th>
        <p> Name </p>
      </th>
      <th>
        <p>Description</p>
      </th>
    </tr>
  </thead>
  <tbody border="1">
    <tr>
      <td>
        <%= @repository[:name] %>
      </td>
      <td>
        <%= @repository[:full_name].present? ? @repository[:full_name] : "N/A"%>
      </td>
    </tr>
  </tbody>
</table>



<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <p>Commit Date</p>
      </th>
      <th>
        <p> Commit Message</p>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @repository_commits.each do |repository_commit| %>
      <tr>
        <td>
          <%= repository_commit[:commit_date].to_time.strftime('%Y-%m-%d') %>
        </td>
        <td>
          <%= repository_commit[:commit_msg] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>